# Generated by Django 4.2.5 on 2023-09-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_id_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='user_image',
        ),
    ]
